-- Ensures projects.project_code is always generated by the database and exposes
-- an RPC (next_project_code) that the frontend can call before inserting.

create sequence if not exists public.project_code_seq
    increment by 1
    minvalue 1
    start with 1
    cache 1;

-- Align the sequence with the current maximum project_code.
select setval(
    'public.project_code_seq',
    coalesce(
        (select max(project_code::bigint) from public.projects where project_code is not null),
        0
    )
);

alter table public.projects
    alter column project_code type bigint using project_code::bigint,
    alter column project_code set not null,
    alter column project_code set default nextval('public.project_code_seq');

create or replace function public.next_project_code()
returns bigint
language sql
security definer
set search_path = public
as $$
    select nextval('public.project_code_seq');
$$;

grant execute on function public.next_project_code() to anon, authenticated, service_role;
