// This file is automatically generated by the build process
// It ensures environment variables are available at runtime

// Note: Window.__ENV type is defined in src/types.d.ts

export const GEMINI_API_KEY = 
  typeof window !== 'undefined' && window.__ENV?.VITE_GEMINI_API_KEY 
    ? window.__ENV.VITE_GEMINI_API_KEY 
    : '';

export const IS_AI_DISABLED = (
  (typeof window !== 'undefined' && window.__ENV?.VITE_AI_OFF === '1') ||
  (typeof window !== 'undefined' && window.__ENV?.VITE_IS_AI_DISABLED === 'true') ||
  (typeof window !== 'undefined' && window.__ENV?.NEXT_PUBLIC_AI_OFF === '1') ||
  false
);

// Log the resolved values in development
if (process.env.NODE_ENV === 'development') {
  console.log('AI Configuration:', {
    GEMINI_API_KEY: GEMINI_API_KEY ? '***' : 'Not set',
    IS_AI_DISABLED,
  });
}
